name: Test EC2_SSH_KEY Secret

on:
  push:
    branches:
      - main

jobs:
  test-secret:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Debug Secrets
      run: |
        echo "Checking if EC2_SSH_KEY is set"
        if [ -z "${{ secrets.EC2_SSH_KEY }}" ]; then
          echo "EC2_SSH_KEY is not set or is empty"
          exit 1
        else
          echo "EC2_SSH_KEY is set"
        fi
