name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # or the version your application needs

    - name: Install dependencies
      run: npm install

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Copy files via SCP
      run: scp -o StrictHostKeyChecking=no -r ./* ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/app

    - name: Deploy application
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          # Install Node.js
          curl -sL https://rpm.nodesource.com/setup_14.x | sudo -E bash -
          sudo yum install -y nodejs

          # Install PM2
          sudo npm install -g pm2

          # Navigate to app directory
          cd /home/${{ secrets.EC2_USER }}/app

          # Create .env file
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "MONGO_URL=${{ secrets.MONGO_URL }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env

          # Install dependencies
          npm install

          # Stop the existing application
          pm2 stop all || true

          # Start the application using pm2
          pm2 start app.js --name iks --watch --no-daemon --env production

        EOF
