name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Debug SSH connection (optional)
      env:
        PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}  # Reference from Secrets Manager
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        echo "Host is set to: $HOST"
        echo "User is set to: $USER"
        # Optional: Verify private key presence and format (replace with your preferred command)
        # openssl rsa -in ${{ secrets.EC2_PRIVATE_KEY }} -check

    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
      run: |
        # Use AWS CLI or another tool to retrieve the private key content securely
        PRIVATE_KEY_CONTENT=$(aws secretsmanager get-secret-value --secret-id "ec2-private-key" --query SecretString --output text)
        echo "$PRIVATE_KEY_CONTENT" > private_key
        chmod 600 private_key
        ssh -o StrictHostKeyChecking=ask -i private_key ${USER}@${HOST} '
          cd /home/ubuntu/backend-deployment &&
          git pull origin main &&
          npm install &&
          pm2 restart app.js
        '
