name: Test Environment Secrets

on:
  push:
    branches:
      - main

jobs:
  test-environment-secrets:
    runs-on: ubuntu-latest

    environment: AWS EC2 CI/CD

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Test Access to Secrets
      run: |
        echo "Checking if EC2_USER is set"
        if [ -z "${{ secrets.EC2_USER }}" ]; then
          echo "EC2_USER is not set or is empty"
          exit 1
        else
          echo "EC2_USER is set"
        fi
        echo "Checking if EC2_SSH_KEY is set"
        if [ -z "${{ secrets.EC2_SSH_KEY }}" ]; then
          echo "EC2_SSH_KEY is not set or is empty"
          exit 1
        else
          echo "EC2_SSH_KEY is set"
        fi
