name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: AWS EC2 CI/CD

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # or the version your application needs

    - name: Install dependencies
      run: npm install

    - name: Debug Secrets
      run: |
        echo "EC2_USER=${{ secrets.EC2_USER }}"
        echo "EC2_HOST=${{ secrets.EC2_HOST }}"
        echo "EC2_SSH_KEY is set"  # We confirmed this in the previous test
      shell: bash

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Copy files via SCP
      env:
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
      run: scp -o StrictHostKeyChecking=no -r ./* $EC2_USER@$EC2_HOST:/home/$EC2_USER/app

    - name: Deploy application
      env:
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        PORT: ${{ secrets.PORT }}
        MONGO_URL: ${{ secrets.MONGO_URL }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
      run: |
        ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
          # Install Node.js
          curl -sL https://rpm.nodesource.com/setup_14.x | sudo -E bash -
          sudo yum install -y nodejs

          # Install PM2
          sudo npm install -g pm2

          # Navigate to app directory
          cd /home/$EC2_USER/app

          # Create .env file
          echo "PORT=${PORT}" > .env
          echo "MONGO_URL=${MONGO_URL}" >> .env
          echo "JWT_SECRET=${JWT_SECRET}" >> .env

          # Install dependencies
          npm install

          # Stop the existing application
          pm2 stop all || true

          # Start the application using pm2
          pm2 start app.js --name iks --watch --no-daemon --env production

        EOF
